[workspace]
members = ["crates/rustson"]

[package]
name = "rust_learn"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rustson"
path = "crates/rustson/src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
